  
name: Python Checking

on: [push, pull_request]

jobs:
  analyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Common dependencies
      run: |
        python -m pip install --upgrade pip
        cd common_scripts
        pip install .
    - name: Install Module dependencies
      run: |
        pip install -r km/scripts/requirements.txt
        pip install -r contract/scripts/requirements.txt
        pip install -r worker/scripts/requirements.txt
        pip install -r client/scripts/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        # flake8 --count --select=E9,F63,F7,F82 --show-source --statistics common_scripts/enigma_docker_common
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --exclude __init__.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics ./common_scripts/enigma_docker_common/ ./km/scripts/ ./contract/scripts/ ./client/scripts/ ./worker/scripts/
    - name: Lint with pylint
      run: |
        pip install pylint
        # stop the build if there are Python syntax errors or undefined names
        pylint --rcfile .pylintrc --exit-zero ./common_scripts/enigma_docker_common/ ./km/scripts/ ./contract/scripts/ ./client/scripts/ ./worker/scripts/
    - name: Typecheck with mypy
      run: |
        pip install mypy
        # stop the build if there are Python syntax errors or undefined names
        mypy ./common_scripts/enigma_docker_common/
        mypy ./km/scripts
        mypy ./contract/scripts
        mypy ./client/scripts
        mypy ./worker/scripts
    - name: Safety Check
      run: |
        pip install safety
        safety check 
